apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  name: redis
  namespace: ocu--staging-webapp
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    service: redis